"use client"

import { createContext, useContext, useEffect, useState } from "react"
import type { ReactNode } from "react"

export type Lang = "FR" | "EN"

// ── All translations ──────────────────────────────────────────
export const T = {
  FR: {
    nav: {
      home: "Accueil",
      matches: "Matchs",
      signals: "Signaux",
      bets: "Paris",
      rooms: "Salles",
    },
    intro: {
      l0: "Les gagnants n'ont pas plus de chance. Ils ont plus d'informations.",
      l1: "Compositions réelles · Blessures cachées · Tensions de vestiaire · Forme des joueurs · Signaux de value en direct.",
      l2: "Arrêtez de parier. Commencez à investir.",
    },
    analysis: {
      title: "Intelligence Briefing",
      balance: "Solde",
      signals: "Signaux du Jour",
      noSignals: "Aucun signal pour aujourd'hui",
      noSignalsHint: "Les agents analysent les matchs à 08:00",
      analyze: "Analyser",
      addCoupon: "Coupon",
      removeCoupon: "Retirer",
      myCoupon: "Mon Coupon",
      potentialWin: "Gain potentiel",
      validateCoupon: "Valider le coupon →",
      clearCoupon: "Vider",
      stakeIn: "Mise en",
      aiYesterday: "IA hier",
      correct: "corrects",
      accuracy30: "Précision 30j",
      signalStrong: "SIGNAL FORT",
      signalMedium: "SIGNAL MOYEN",
      signalWeak: "SIGNAL FAIBLE",
      confHigh: "Haute",
      confMid: "Moyenne",
      confLow: "Faible",
      accExcellent: "Excellente",
      accGood: "Bonne",
      burstModeActive: "Burst Mode Actif",
      burstModeHint: "Invocations illimitées LIVE",
      fullAnalysis: "Analyse Complète (14 agents)",
      analyzing: "Analyse...",
      agentAnalyzing: "Agent en cours d'analyse…",
      compareAgents: "Comparer les agents",
      matchLoaded: "Match chargé",
      noMatchHint: 'Cliquez sur "Analyser" sur un signal pour charger un match',
      noMatchHint2: "ou tapez @AgentName dans le chat",
      backToSignals: "← Signaux",
      noSpeech: "Votre navigateur ne supporte pas la reconnaissance vocale.",
      micDenied: "Accès micro refusé.",
      ttsNotSupported: "TTS non supporté",
      inputPlaceholder: "@AgentName — ex: @Scout analyse ce match",
      launchFullAnalysis: "Lancer l'analyse complète ?",
      agentsWillAnalyze: "agents vont analyser",
      thisMatch: "ce match",
      cancel: "Annuler",
      launch: "Lancer",
      agentComparison: "Comparaison des Agents",
      consensusIndicator: "Indicateur de consensus",
      strongConsensus: "✅ Fort consensus",
      moderateConsensus: "⚖️ Consensus modéré",
      divergingOpinions: "⚠️ Opinions divergentes",
      avgConfidence: "Confiance moyenne",
      stdDev: "écart-type",
      insufficientData: "⏳ Données insuffisantes",
      predictionsMinimum: "prédictions (minimum 30 requis)",
      overallAccuracy: "Précision Globale",
      recentForm: "Forme Récente (30j)",
      result: "Résultat",
      goals: "Buts",
      corners: "Corners",
      cards: "Cartes",
      addedValue: "Valeur ajoutée vs hasard (50%)",
      predictionsAnalyzed: "prédictions analysées",
      burstModePremium: "Burst Mode Premium",
      liveMatchDetected: "Match LIVE détecté ! Débloquez l'accès illimité aux agents pendant les matchs en direct.",
      later: "Plus tard",
      goPremium: "Passer Premium",
    },
    matches: {
      title: "Matchs",
      finished: "Terminé",
      upcoming: "À venir",
      analyze: "Analyser",
      added: "Ajouté",
      addToCoupon: "Coupon",
      allCountries: "Tous les pays",
      country: "Pays",
      competition: "Compétition",
      allCompetitions: "Toutes les compétitions",
      clear: "Effacer",
      clearFilters: "Effacer les filtres",
      refreshing: "Actualisation…",
      demoData: "Données de démonstration",
      retry: "Réessayer",
      noResults: "Aucun résultat pour",
      noMatchesPeriod: "Aucun match pour cette période",
      today: "Aujourd'hui",
      searchPlaceholder: "Équipe, compétition...",
    },
    signaux: {
      title: "Intelligence Briefing",
      todayBadge: "Aujourd'hui",
      historyBadge: "Historique",
      signals: "Signaux",
      report: "Rapport",
      agentsAgree: "agents en accord",
      noSignalForDate: "Aucun signal pour le",
    },
    paris: {
      virtualBets: "Paris Virtuels",
      tabCoupon: "Coupon",
      tabPending: "En cours",
      tabHistory: "Historique",
      emptyCoupon: "Coupon vide",
      addMatchesHint: "Ajoute des matchs depuis la page Matchs",
      seeMatches: "Voir les matchs",
      oddsSelected: "cotes sélectionnées",
      totalOdds: "Cote totale",
      stake: "Mise",
      potentialWin: "Gain potentiel",
      insufficientBalance: "Solde insuffisant — max",
      clear: "Vider",
      validateCoupon: "Valider le coupon",
      noPendingBets: "Aucun pari en cours",
      pendingHint: "Tes coupons actifs apparaîtront ici",
      noHistory: "Aucun historique",
      historyHint: "Tes coupons terminés apparaîtront ici",
      combinedCoupon: "Coupon combiné",
      noOdds: "Cotes non disponibles",
      draw: "Nul",
      couponPlaced: "Coupon placé — Gain potentiel",
      unexpectedError: "Erreur inattendue — réessaie",
      statusPending: "En cours",
      statusWon: "Gagné",
      statusLost: "Perdu",
      statusCancelled: "Annulé",
    },
    salles: {
      title: "Salles",
      createBtn: "Créer",
      myRooms: "Mes Salles",
      explore: "Explorer",
      searchPlaceholder: "Rechercher une salle...",
      noRooms: "Aucune salle",
      noRoomsHint: "Rejoignez une salle depuis l'onglet Explorer",
      exploreRooms: "Explorer les salles",
      official: "Officiel",
      members: "membre",
      officialRooms: "Salles Officielles",
      communityRooms: "Salles Communautaires",
      access: "Accéder →",
      join: "Rejoindre",
      inviteOnly: "🔒 Sur invitation",
      createdBy: "Créé par",
      noResults: "Aucun résultat pour",
      noRoomsAvailable: "Aucune salle disponible",
      tryAnotherSearch: "Essayez un autre terme de recherche",
      roomsWillAppear: "Les salles apparaîtront ici",
      createRoom: "Créer une salle",
      roomName: "Nom de la salle *",
      description: "Description",
      optional: "optionnel",
      visibility: "Visibilité",
      visPublic: "🌍 Publique",
      visPrivate: "🔒 Privée",
      visInvite: "✉️ Invitation",
      visPublicLabel: "Publique",
      visPrivateLabel: "Privée",
      visInviteLabel: "Invitation",
      creating: "Création...",
      create: "Créer la salle",
      descriptionPlaceholder: "Décrivez votre salle...",
    },
    oracle: {
      agentSelector: "CHOISIR UN AGENT",
      agentsReady: "14 agents prêts à analyser",
      agentsReadyLong: "14 agents prêts à analyser le match pour vous",
      agentActive: "actif",
      agentActivated: "activé",
      analyzingVia: "Analyse en cours via @GoalMaster + @TacticMaster…",
      processing: "traite ta requête — conf 78%",
      generalAgent: "Généraliste · routage auto",
      messagePlaceholder: "Tape ton message ici…",
      matchReady: "chargé et prêt pour l'analyse ! Je coordonne les 14 agents spécialisés. Quel aspect veux-tu creuser ? (buts, corners, cartons, tactique…) Ou @mentionne directement un agent.",
      newConversation: "Nouvelle conversation",
      history: "Historique des conversations",
      noHistory: "Aucune conversation récente.",
      rename: "Renommer",
      delete: "Supprimer",
    },
  },
  EN: {
    nav: {
      home: "Home",
      matches: "Matches",
      signals: "Signals",
      bets: "Bets",
      rooms: "Rooms",
    },
    intro: {
      l0: "Winners don't have more luck. They have more information.",
      l1: "Real lineups · Hidden injuries · Locker room tensions · Player form · Live value signals.",
      l2: "Stop gambling. Start investing.",
    },
    analysis: {
      title: "Intelligence Briefing",
      balance: "Balance",
      signals: "Today's Signals",
      noSignals: "No signals for today",
      noSignalsHint: "Agents analyze matches at 08:00",
      analyze: "Analyze",
      addCoupon: "Add",
      removeCoupon: "Remove",
      myCoupon: "My Coupon",
      potentialWin: "Potential win",
      validateCoupon: "Confirm coupon →",
      clearCoupon: "Clear",
      stakeIn: "Stake in",
      aiYesterday: "AI yesterday",
      correct: "correct",
      accuracy30: "30d accuracy",
      signalStrong: "STRONG SIGNAL",
      signalMedium: "MEDIUM SIGNAL",
      signalWeak: "WEAK SIGNAL",
      confHigh: "High",
      confMid: "Medium",
      confLow: "Low",
      accExcellent: "Excellent",
      accGood: "Good",
      burstModeActive: "Burst Mode Active",
      burstModeHint: "Unlimited LIVE invocations",
      fullAnalysis: "Full Analysis (14 agents)",
      analyzing: "Analyzing...",
      agentAnalyzing: "Agent analyzing…",
      compareAgents: "Compare agents",
      matchLoaded: "Match loaded",
      noMatchHint: 'Click "Analyze" on a signal to load a match',
      noMatchHint2: "or type @AgentName in chat",
      backToSignals: "← Signals",
      noSpeech: "Your browser does not support speech recognition.",
      micDenied: "Microphone access denied.",
      ttsNotSupported: "TTS not supported",
      inputPlaceholder: "@AgentName — e.g: @Scout analyze this match",
      launchFullAnalysis: "Launch full analysis?",
      agentsWillAnalyze: "agents will analyze",
      thisMatch: "this match",
      cancel: "Cancel",
      launch: "Launch",
      agentComparison: "Agent Comparison",
      consensusIndicator: "Consensus Indicator",
      strongConsensus: "✅ Strong consensus",
      moderateConsensus: "⚖️ Moderate consensus",
      divergingOpinions: "⚠️ Diverging opinions",
      avgConfidence: "Average confidence",
      stdDev: "std dev",
      insufficientData: "⏳ Insufficient data",
      predictionsMinimum: "predictions (minimum 30 required)",
      overallAccuracy: "Overall Accuracy",
      recentForm: "Recent Form (30d)",
      result: "Result",
      goals: "Goals",
      corners: "Corners",
      cards: "Cards",
      addedValue: "Added value vs random (50%)",
      predictionsAnalyzed: "predictions analyzed",
      burstModePremium: "Burst Mode Premium",
      liveMatchDetected: "LIVE match detected! Unlock unlimited agent access during live matches.",
      later: "Later",
      goPremium: "Go Premium",
    },
    matches: {
      title: "Matches",
      finished: "Finished",
      upcoming: "Upcoming",
      analyze: "Analyze",
      added: "Added",
      addToCoupon: "Coupon",
      allCountries: "All countries",
      country: "Country",
      competition: "Competition",
      allCompetitions: "All competitions",
      clear: "Clear",
      clearFilters: "Clear filters",
      refreshing: "Refreshing…",
      demoData: "Demo data",
      retry: "Retry",
      noResults: "No results for",
      noMatchesPeriod: "No matches for this period",
      today: "Today",
      searchPlaceholder: "Team, competition...",
    },
    signaux: {
      title: "Intelligence Briefing",
      todayBadge: "Today",
      historyBadge: "History",
      signals: "Signals",
      report: "Report",
      agentsAgree: "agents agree",
      noSignalForDate: "No signals for",
    },
    paris: {
      virtualBets: "Virtual Bets",
      tabCoupon: "Coupon",
      tabPending: "Pending",
      tabHistory: "History",
      emptyCoupon: "Empty coupon",
      addMatchesHint: "Add matches from the Matches page",
      seeMatches: "See matches",
      oddsSelected: "odds selected",
      totalOdds: "Total odds",
      stake: "Stake",
      potentialWin: "Potential win",
      insufficientBalance: "Insufficient balance — max",
      clear: "Clear",
      validateCoupon: "Confirm coupon",
      noPendingBets: "No pending bets",
      pendingHint: "Your active coupons will appear here",
      noHistory: "No history",
      historyHint: "Your completed coupons will appear here",
      combinedCoupon: "Combined coupon",
      noOdds: "Odds unavailable",
      draw: "Draw",
      couponPlaced: "Coupon placed — Potential win",
      unexpectedError: "Unexpected error — try again",
      statusPending: "Pending",
      statusWon: "Won",
      statusLost: "Lost",
      statusCancelled: "Cancelled",
    },
    salles: {
      title: "Rooms",
      createBtn: "Create",
      myRooms: "My Rooms",
      explore: "Explore",
      searchPlaceholder: "Search a room...",
      noRooms: "No rooms",
      noRoomsHint: "Join a room from the Explore tab",
      exploreRooms: "Explore rooms",
      official: "Official",
      members: "member",
      officialRooms: "Official Rooms",
      communityRooms: "Community Rooms",
      access: "Access →",
      join: "Join",
      inviteOnly: "🔒 Invite only",
      createdBy: "Created by",
      noResults: "No results for",
      noRoomsAvailable: "No rooms available",
      tryAnotherSearch: "Try a different search term",
      roomsWillAppear: "Rooms will appear here",
      createRoom: "Create a room",
      roomName: "Room name *",
      description: "Description",
      optional: "optional",
      visibility: "Visibility",
      visPublic: "🌍 Public",
      visPrivate: "🔒 Private",
      visInvite: "✉️ Invite only",
      visPublicLabel: "Public",
      visPrivateLabel: "Private",
      visInviteLabel: "Invite only",
      creating: "Creating...",
      create: "Create room",
      descriptionPlaceholder: "Describe your room...",
    },
    oracle: {
      agentSelector: "CHOOSE AN AGENT",
      agentsReady: "14 agents ready to analyze",
      agentsReadyLong: "14 agents ready to analyze the match for you",
      agentActive: "active",
      agentActivated: "activated",
      analyzingVia: "Analyzing via @GoalMaster + @TacticMaster…",
      processing: "processing your query — conf 78%",
      generalAgent: "Generalist · auto-routing",
      messagePlaceholder: "Type your message here…",
      matchReady: "loaded and ready for analysis! I'm coordinating 14 specialized agents. Which aspect do you want to dig into? (goals, corners, cards, tactics…) Or @mention an agent directly.",
      newConversation: "New conversation",
      history: "Conversation History",
      noHistory: "No recent conversations.",
      rename: "Rename",
      delete: "Delete",
    },
  },
}

export type Translations = typeof T.FR

// ── Context ───────────────────────────────────────────────────
interface LangContextValue {
  lang: Lang
  setLang: (l: Lang) => void
  t: Translations
}

const LangContext = createContext<LangContextValue>({
  lang: "FR",
  setLang: () => undefined,
  t: T.FR,
})

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("FR")

  useEffect(() => {
    const stored = localStorage.getItem("betanalytic_lang")
    if (stored === "EN" || stored === "FR") setLangState(stored)

    const handler = (e: StorageEvent) => {
      if (e.key === "betanalytic_lang" && (e.newValue === "EN" || e.newValue === "FR"))
        setLangState(e.newValue)
    }
    window.addEventListener("storage", handler)
    return () => window.removeEventListener("storage", handler)
  }, [])

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem("betanalytic_lang", l)
    window.dispatchEvent(new StorageEvent("storage", { key: "betanalytic_lang", newValue: l }))
  }

  return (
    <LangContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
